spring.application.name=TodoManager

#max file size
spring.servlet.multipart.max-file-size=20MB

#max file request
spring.servlet.multipart.max-request-size=200MB

#url
spring.datasource.url=jdbc:mysql://localhost:3306/boot_cource
spring.datasource.username=root
spring.datasource.password=Yash7105

#configuration of jpa
spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true

#dialect for connection particular language
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

